# Generated by Django 4.2.5 on 2023-09-14 22:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, help_text='Ingrese sin puntos', max_length=8, null=True, verbose_name='D.N.I.')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField(default='10/10/10', help_text='dia/mes/año', max_length=6, verbose_name='Fecha de nacimiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], default='F', max_length=10, null=True)),
                ('vive', models.BooleanField(default=True)),
                ('email', models.EmailField(default='nombre@hotmail.com', max_length=250, unique=True)),
                ('legajo', ckeditor.fields.RichTextField(default='Legajo de Persona')),
                ('foto', models.ImageField(default='imagenes/avatar.png', upload_to='imagenes/', verbose_name='Foto 4x4')),
                
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ('apellido', 'nombre'),
            },
        ),
    ]
