# Generated by Django 4.2.5 on 2023-09-14 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='Personas.estadocivil'),
        ),
    ]
